# Generated by Django 4.1.7 on 2023-03-22 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="time_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
