# Generated by Django 4.1.7 on 2023-03-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_remove_order_favourites_order_favourite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="favourite",
        ),
    ]
