# Generated by Django 4.1.7 on 2023-03-25 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0005_remove_order_favourite"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_favourite",
            field=models.ManyToManyField(
                related_name="favourite", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
