# Generated by Django 4.1.7 on 2023-03-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_order_is_favourite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_favourite",
        ),
        migrations.AddField(
            model_name="order",
            name="is_favourite",
            field=models.BooleanField(default=False),
        ),
    ]
