# Generated by Django 4.1.7 on 2023-03-26 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0007_remove_order_is_favourite_order_is_favourite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_favourite",
        ),
        migrations.AddField(
            model_name="order",
            name="favourites",
            field=models.ManyToManyField(
                blank=None,
                default=None,
                related_name="favourite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
