# Generated by Django 4.1.7 on 2023-03-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_remove_order_is_favourite_order_favourites"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_favourite",
            field=models.BooleanField(default=False),
        ),
    ]
